### ISSUE TITLE
Incorrect debug invocation of `exec:java` on Windows

### ISSUE THREAD

**Issue by ThePrez** [microsoft/vscode-maven#913]
##### Environment
- Operating System: Windows 10
- JDK version: IBM Semeru Runtime Open Edition 11.0.17.0 (build 11.0.17+8)
- Visual Studio Code version: 1.73.1
- Java extension version: v1.13.0
- Java Debugger extension version: v0.47.0

##### Steps To Reproduce
1. In Maven view ---> "Plugins"
2. expand the "exec" plugin
3. Right-click on "java" and go to "Run". Observe that the program runs correctly
4. Right-click on "java" and go to "Debug"

Log info:
```pascal
!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-03 14:59:21.641
!MESSAGE >> workspace/executeCommand vscode.java.startDebugSession

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-03 14:59:23.938
!MESSAGE >> workspace/executeCommand vscode.java.fetchUsageData
```

##### Current Result
`mvn` is invoked with "java" on the command line 
![image](https://user-images.githubusercontent.com/17914061/205461741-b65d55b2-83f2-45e0-aa96-e5321344126c.png)
 (this results in a failure due to "java" being an unknown lifecycle phase)

##### Expected Result
`mvn` is invoked with "exec:java" on the command line, as is done properly when the "run" action is taken from the plugin

##### Additional Informations

pom.xml plugin entry:
```xml
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.1.0</version>
        <configuration>
          <mainClass>io.github.theprez.jtailor.CamelMeUp</mainClass>
          <includePluginDependencies>false</includePluginDependencies>
        </configuration>
      </plugin>
```

**Comment by Eskibear** [comment]
@ThePrez What's the version of your installed "Maven for Java" extension?

It's fixed in v0.40.1. See https://github.com/microsoft/vscode-maven/issues/910

**Comment by ThePrez** [comment]
> @ThePrez What's the version of your installed "Maven for Java" extension?
> 
> It's fixed in v0.40.1. See #910

I am running `v0.40.1`. I also tried `v0.40.2022120203` as the most recent release and see the behavior there as well. Uninstalling/reinstalling also does not fix. I also looked in the installed JS on my PC at `%USERPROFILE%\.vscode\extensions\vscjava.vscode-maven-0.40.1\dist\extension.js` and verified that [the code fix](https://github.com/microsoft/vscode-maven/commit/a52340546f08cf05793466f97c9c43958442b0ad) is there, but the faulty behavior persists. 

Upon cursory inspection of the code, I am curious if the check [here](https://github.com/microsoft/vscode-maven/blob/a52340546f08cf05793466f97c9c43958442b0ad/src/explorer/model/PluginGoal.ts#L25) is being incorrectly triggered because my maven command, having a fully-qualified Windows path, contains a `:` (actually two: one for the maven command and one for the fully-qualified path to the pom.xml). I can't figure out a way to test this hypothesis configuration or command line options, though.

**Comment by ThePrez** [comment]
> Upon cursory inspection of the code, I am curious if the check [here](https://github.com/microsoft/vscode-maven/blob/a52340546f08cf05793466f97c9c43958442b0ad/src/explorer/model/PluginGoal.ts#L25) is being incorrectly triggered because my maven command, having a fully-qualified Windows path, contains a `:` (actually two: one for the maven command and one for the fully-qualified path to the pom.xml). 

After some more code inspection, I don't think this is it. :/

**Comment by Eskibear** [comment]
I just tried the `exec-maven-plugin` as you mentioned above but failed to reproduce the issue, it ran `exec:java` as expected.

Can you check if your maven explorer looks like below? i.e. parent node of `java` is `exec`. 
![image](https://user-images.githubusercontent.com/2351748/205543088-3e9cce17-4708-4e53-b5b3-09a104db3a66.png)

**Comment by Eskibear** [comment]
Ok now I can reproduce it. It only occur when you "debug" it instead of "run".

**Comment by Eskibear** [comment]
@ThePrez 

It's fixed and shipped in v0.40.2022120507. You can switch to pre-release version to try it.

**Comment by ThePrez** [comment]
Works beautifully. Thanks!
